//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gameManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class gameDox
    {
        public int Id { get; set; }
        public string Game { get; set; }
        public string Developer { get; set; }
        public string Genre { get; set; }
        public string Platform { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> AgeRating { get; set; }
        public Nullable<decimal> Score { get; set; }
        public string GameMode { get; set; }
        public Nullable<int> Stock { get; set; }
    }
}
